export type AppErrorCode =
  | "MALFORMED_JSON"
  | "UNAUTHENTICATED"
  | "INVALID_CREDENTIALS"
  | "DOCUMENT_NOT_FOUND"
  | "LINE_NOT_FOUND"
  | "ROUTE_NOT_FOUND"
  | "EMAIL_ALREADY_REGISTERED"
  | "FINALIZED_DOCUMENT_IMMUTABLE"
  | "DOCUMENT_ALREADY_FINALIZED"
  | "PAYLOAD_TOO_LARGE"
  | "VALIDATION_ERROR"
  | "INVALID_QUANTITY"
  | "INVALID_UNIT_PRICE"
  | "INVALID_PERCENT"
  | "INVALID_DISCOUNT_SHAPE"
  | "INVALID_DISCOUNT_VALUE"
  | "DISCOUNT_EXCEEDS_SUBTOTAL"
  | "TOO_MANY_LINES"
  | "DOCUMENT_HAS_NO_LINES"
  | "STATUS_NOT_PATCHABLE"
  | "INVALID_DATE_RANGE"
  | "RATE_LIMITED"
  | "INTERNAL_ERROR";

export interface AppError {
  code: AppErrorCode;
  message: string;
  field?: string;
}

export const ERROR_STATUS: Record<AppErrorCode, number> = {
  MALFORMED_JSON: 400,
  UNAUTHENTICATED: 401,
  INVALID_CREDENTIALS: 401,
  DOCUMENT_NOT_FOUND: 404,
  LINE_NOT_FOUND: 404,
  ROUTE_NOT_FOUND: 404,
  EMAIL_ALREADY_REGISTERED: 409,
  FINALIZED_DOCUMENT_IMMUTABLE: 409,
  DOCUMENT_ALREADY_FINALIZED: 409,
  PAYLOAD_TOO_LARGE: 413,
  VALIDATION_ERROR: 422,
  INVALID_QUANTITY: 422,
  INVALID_UNIT_PRICE: 422,
  INVALID_PERCENT: 422,
  INVALID_DISCOUNT_SHAPE: 422,
  INVALID_DISCOUNT_VALUE: 422,
  DISCOUNT_EXCEEDS_SUBTOTAL: 422,
  TOO_MANY_LINES: 422,
  DOCUMENT_HAS_NO_LINES: 422,
  STATUS_NOT_PATCHABLE: 422,
  INVALID_DATE_RANGE: 422,
  RATE_LIMITED: 429,
  INTERNAL_ERROR: 500,
};
